# syntax=docker/dockerfile:1

# --- Image
FROM ubuntu:focal
LABEL maintainers="carlo.corradini@studenti.unitn.it, nicolo.vinci@studenti.unitn.it" \
    name="Host" \
    version="0.0.1"
# Working directory
WORKDIR /root/host

# --- Packages
RUN apt-get update \
    && apt-get install -y \
    iperf3 \
    iproute2 \
    iputils-ping \
    net-tools \
    tcpdump \
    macchanger \
    traceroute \
    curl

# --- CLEAN
RUN apt-get clean

# --- BOOTSTRAP
CMD ["bash"]
