# syntax=docker/dockerfile:1

# --- Image
FROM python:3.9-alpine
LABEL maintainers="carlo.corradini@studenti.unitn.it, nicolo.vinci@studenti.unitn.it" \
    name="Server" \
    version="0.0.1"
# Working directory
WORKDIR /app

# --- Copy
COPY server.py server.py

# --- Python
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    Flask \
    requests

# --- Run
EXPOSE 80
ENTRYPOINT ["python3", "/app/server.py"]
