name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install ruby-dev shellcheck
        shell: bash

      - name: Install pipenv
        run: pipx install pipenv

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pipenv"

      - name: Install Python packages
        run: pipenv install --dev

      - name: pre-commit
        run: pipenv run pre-commit run --all-files
