name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: macos-10.15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Scripts permissions
        run: chmod -R +x scripts

      - name: Cache Vagrant boxes
        uses: actions/cache@v2
        with:
          path: ~/.vagrant.d/boxes
          key: ${{ runner.os }}-vagrant-${{ hashFiles('Vagrantfile') }}
          restore-keys: |
            ${{ runner.os }}-vagrant-

      - name: Vagrant version
        run: vagrant --version

      - name: Initialize
        run: scripts/init.sh

      - name: pre-commit
        run: python scripts/deps/pre-commit.pyz run --all-files
