name: release

on:
  workflow_run:
    workflows: [ci]
    types: [completed]
  push:
    tags: [v*.*.*]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Install pipenv
        run: pipx install pipenv

      - name: Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          cache: "pipenv"

      - name: Scripts permissions
        run: chmod -R +x scripts

      - name: Generate morphing_slices.tar.gz
        run: scripts/prod.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body: Morphing Slices ${{ env.RELEASE_VERSION }}
          files: |
            morphing_slices.tar.gz
            LICENSE
